Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Sitegeist.FocusPoints': ['NodeTypes/*']

Sitegeist:
  CsvPO:
    management:
      packageKeys:
        - 'Sitegeist.FocusPoints'
