Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          'rte':
            'plain':
              type: string
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    autoparagraph: false
                    formatting:
                      sub: true
                      sup: true
                      removeFormat: true
            'rich':
              type: 'string'
              ui:
                inlineEditable: true
                inline:
                  editorOptions:
                    autoparagraph: true
                    linking:
                      anchor: true
                      title: true
                      relNofollow: true
                      targetBlank: true
                    formatting:
                      strong: true
                      p: true
                      ol: true
                      ul: true
                      sub: true
                      sup: true
                      a: true
                      em: true
                      table: true
                      pre: true
                      underline: true
                      strikethrough: true
                      removeFormat: true
