name: QA

on: [push, pull_request]

jobs:
  fe-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup DDEV
        uses: jonaseberle/github-action-setup-ddev@v1

      - run: ddev composer install
      - run: ddev yarn

      - run: ddev flow doctrine:migrate

      - run: ddev flow site:import --package-key Vendor.WheelInventor

      - run: make build

      - run: ddev yarn test
