name: QA

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  fe-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup DDEV
        uses: jonaseberle/github-action-setup-ddev@v1

      - run: ddev composer install
      - run: ddev composer lint
      - run: ddev composer test

      - run: ddev yarn
      - run: ddev yarn build
      - run: ddev yarn lint
      - run: ddev yarn test
